### ISSUE TITLE
Can't load data pack when creating a new world 

### ISSUE THREAD

**Issue by IgorIngvar** [GamingCrew69/VanillaForged#2]
Can't load version alpha 2 or alpha 3 (version 1.2 of vanillaForged works fine) when creating new world, an error pops up saying: 'Data Pack validation failed!'. What can I do in this situation to make it work on newer version of this datapack.

**Comment by equalizer32** [comment]
VanillaForged 2.0 was made for an unreleased version of ReTerraForged that was only accesible by building from source. VanillaForged 1.2 is the one you're supposed to be using.
